name: Prerelease

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        archetect-options:
          - "-s github -s serverless -a repository-name=test-sls-rest-api"
          - "-s github -s serverless -a repository-name=test-sls-rest-api -a auth=true"
          - "-s github -s serverless -a repository-name=test-sls-rest-api -a persistence=dynamodb"
          - "-s github -s serverless -a repository-name=test-sls-rest-api -a persistence=dynamodb -a auth=true"
          - "-s github -s serverless -s entity -a repository-name=test-sls-rest-api -a persistence=dynamodb -a entities=foo"
          - "-s github -s serverless -s entity -a repository-name=test-sls-rest-api -a persistence=dynamodb -a entities=foo -a auth=true"
          - "-s github -s serverless -s entity -a repository-name=test-sls-rest-api -a persistence=dynamodb -a entities=foo,bar"
          - "-s github -s serverless -s entity -a repository-name=test-sls-rest-api -a persistence=dynamodb -a entities=foo,bar -a auth=true"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: scaffoldly/archetect-render-action@v1
        with:
          source: "."
          destination: "${{ runner.temp }}/rendered"
          options: "${{ matrix.archetect-options }}"
          commit: "false"
          post-render-command: "npx eslint '*/**/*.{js,ts,tsx}' --fix && npx prettier --write '*/**/*.{js,ts,tsx}'"
      - run: yarn
        working-directory: "${{ runner.temp }}/rendered"
  prerelease:
    needs: render
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: scaffoldly/bump-version-action@v1
        with:
          action: prerelease
          version-file: sly.json
          repo-token: ${{ secrets.GITHUB_TOKEN }}